# FAERS PostgreSQL Exploration

This notebook runs the exploration sections defined in `data/faers_explore.py` against the PostgreSQL `faers` schema.

Prerequisites:
- `.env` contains `POSTGRES_URI`
- the FAERS tables have already been loaded into PostgreSQL
- the notebook kernel uses the MedLens project environment

In [1]:
import importlib
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'data' / 'faers_explore.py').exists():
    raise RuntimeError('Open this notebook from the MedLens workspace root so imports resolve correctly.')

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

PROJECT_ROOT

PosixPath('/home/ashu/github/MedLens')

In [2]:
from data import faers_explore as explore

importlib.reload(explore)

print(f'Using schema: {explore.SCHEMA}')
explore.query("SELECT current_database() AS database_name, current_user AS db_user, current_schema() AS current_schema")

Using schema: faers

  database_name   db_user current_schema
0       medlens  medadmin         public

## 1. Schema Overview
Row counts, table sizes, and the loaded event date range.

In [3]:
schema_counts = explore.section_schema_overview()
schema_counts

========================================================================
  1. Schema overview — tables in `faers`
========================================================================
table_name   size  est_rows
      drug 179 MB   1909327
      reac  91 MB   1445416
      indi  86 MB   1186115
      ther  36 MB    594449
      demo  33 MB    406184
      outc  15 MB    295044

========================================================================
  1b. Exact row counts
========================================================================
table    rows
 drug 1909327
 reac 1445416
 indi 1186115
 ther  594449
 demo  406184
 outc  295044

========================================================================
  1c. Date range of loaded reports
========================================================================
earliest_event latest_event  distinct_months
        102312       502309              344

  table     rows
0  drug  1909327
1  reac  1445416
2  indi  1186115
3  ther   594449
4  demo   406184
5  outc   295044

## 2. Null Rates
Coverage for the MedLens-relevant columns across each FAERS table.

In [4]:
null_rates = explore.section_null_rates()
null_rates

========================================================================
  2. Null rates for MedLens-relevant columns
========================================================================
table           column   total  populated  pct_populated
 demo              age  406184     248412           61.2
 demo          age_grp  406184     122139           30.1
 demo              sex  406184     343640           84.6
 demo               wt  406184      68664           16.9
 demo reporter_country  406184     406184          100.0
 demo         occp_cod  406184     399340           98.3
 drug         drugname 1909327    1909327          100.0
 drug          prod_ai 1909327    1875580           98.2
 drug         role_cod 1909327    1909327          100.0
 drug            route 1909327    1376209           72.1
 drug         dose_amt 1909327     794257           41.6
 drug        dose_unit 1909327     794257           41.6
 reac               pt 1445416    1445416          100.0
 reac     drug_rec_act 1445416       1082            0.1
 outc         outc_cod  295044     295044          100.0
 ther         start_dt  594449     551638           92.8
 ther           end_dt  594449     221632           37.3
 ther              dur  594449     174442           29.3
 indi          indi_pt 1186115    1186115          100.0

   table            column    total  populated  pct_populated
0   demo               age   406184     248412           61.2
1   demo           age_grp   406184     122139           30.1
2   demo               sex   406184     343640           84.6
3   demo                wt   406184      68664           16.9
4   demo  reporter_country   406184     406184          100.0
5   demo          occp_cod   406184     399340           98.3
6   drug          drugname  1909327    1909327          100.0
7   drug           prod_ai  1909327    1875580           98.2
8   drug          role_cod  1909327    1909327          100.0
9   drug             route  1909327    1376209           72.1
10  drug          dose_amt  1909327     794257           41.6
11  drug         dose_unit  1909327     794257           41.6
12  reac                pt  1445416    1445416          100.0
13  reac      drug_rec_act  1445416       1082            0.1
14  outc          outc_cod   295044     295044          100.0
15  ther          start_dt   594449     551638           92.8
16  ther            end_dt   594449     221632           37.3
17  ther               dur   594449     174442           29.3
18  indi           indi_pt  1186115    1186115          100.0

## 3. Role Codes
How FDA labels each drug mention: primary suspect, secondary suspect, concomitant, or interacting.

In [5]:
role_codes = explore.section_role_codes()
role_codes

========================================================================
  3. role_cod distribution (which drugs FDA blames)
========================================================================
role_cod  mentions   pct
      SS    819690 42.93
       C    672903 35.24
      PS    406273 21.28
       I     10461  0.55

========================================================================
  3b. FDA-flagged drug-drug interaction cases (role='I')
========================================================================
 ddi_cases  ddi_drug_mentions
      2327              10461

  role_cod  mentions    pct
0       SS    819690  42.93
1        C    672903  35.24
2       PS    406273  21.28
3        I     10461   0.55

## 4. Outcome Severity
FDA outcome codes grouped into the Major, Moderate, and Minor buckets used in MedLens.

In [6]:
outcomes = explore.section_outcomes()
outcomes

========================================================================
  4. outc_cod distribution — training severity labels
========================================================================
severity outc_cod      n
   Major       HO  82534
   Major       DE  32303
   Major       LT  11990
Moderate       DS   6112
Moderate       RI    981
Moderate       CA    895
   Minor       OT 160229

========================================================================
  4b. Cases with multiple outcomes (e.g. DE + HO)
========================================================================
 n_outcomes  cases
          1 162690
          2  49210
          3   8624
          4   1280
          5    418
          6    142

   severity outc_cod       n
0     Major       HO   82534
1     Major       DE   32303
2     Major       LT   11990
3  Moderate       DS    6112
4  Moderate       RI     981
5  Moderate       CA     895
6     Minor       OT  160229

## 5. Drug Name Normalization
Compare reporter-entered brand names with FDA-normalized active ingredients.

In [7]:
drug_names = explore.section_drug_names()
drug_names

========================================================================
  5. Drug name vs active ingredient
========================================================================
 total_mentions  distinct_drugnames  distinct_ingredients pct_ai_populated
        1909327               27674                  6431             98.2

========================================================================
  5b. Top 20 active ingredients by mention count
========================================================================
                 prod_ai  mentions  n_brand_variants
             TIRZEPATIDE     76176                 3
         INFLIXIMAB-DYYB     41639                 2
               DUPILUMAB     33387                 2
              PREDNISONE     22792                 4
           ACETAMINOPHEN     21185                31
            METHOTREXATE     20103                 3
             VEDOLIZUMAB     20060                 2
              OMALIZUMAB     16025                 2
               RITUXIMAB     14711                 3
              EVOLOCUMAB     14039                 2
             TOCILIZUMAB     13439                 3
            LENALIDOMIDE     13303                 2
             TEDUGLUTIDE     11669                 1
              ADALIMUMAB     11656                 2
                 ASPIRIN     11374                23
CETIRIZINE HYDROCHLORIDE     11228                11
     TOFACITINIB CITRATE     11078                 3
           DEXAMETHASONE     10853                 7
         CHOLECALCIFEROL     10031                 2
     AMLODIPINE BESYLATE      9953                 3

========================================================================
  5c. Example brand variants for a common ingredient (ACETAMINOPHEN)
========================================================================
                   drugname     n
              ACETAMINOPHEN 14421
                    TYLENOL  4497
     TYLENOL EXTRA STRENGTH   660
                  DOLIPRANE   292
                   DAFALGAN   262
                    CALONAL   256
TYLENOL 8 HR ARTHRITIS PAIN   192
     TYLENOL ARTHRITIS PAIN   153
                    PANADOL    85
                  PERFALGAN    66
                TYLENOL 8HR    63
   TYLENOL REGULAR STRENGTH    62
          CHILDRENS TYLENOL    35
                       APAP    30
                    OFIRMEV    27

                     prod_ai  mentions  n_brand_variants
0                TIRZEPATIDE     76176                 3
1            INFLIXIMAB-DYYB     41639                 2
2                  DUPILUMAB     33387                 2
3                 PREDNISONE     22792                 4
4              ACETAMINOPHEN     21185                31
5               METHOTREXATE     20103                 3
6                VEDOLIZUMAB     20060                 2
7                 OMALIZUMAB     16025                 2
8                  RITUXIMAB     14711                 3
9                 EVOLOCUMAB     14039                 2
10               TOCILIZUMAB     13439                 3
11              LENALIDOMIDE     13303                 2
12               TEDUGLUTIDE     11669                 1
13                ADALIMUMAB     11656                 2
14                   ASPIRIN     11374                23
15  CETIRIZINE HYDROCHLORIDE     11228                11
16       TOFACITINIB CITRATE     11078                 3
17             DEXAMETHASONE     10853                 7
18           CHOLECALCIFEROL     10031                 2
19       AMLODIPINE BESYLATE      9953                 3

## 6. Polypharmacy Signal
Distribution of suspect-drug counts per case and how they align with outcome severity.

In [8]:
polypharmacy = explore.section_polypharmacy()
polypharmacy

========================================================================
  6. Polypharmacy: distribution of suspect drugs per case
========================================================================
         bucket  cases  pct
1 (monotherapy) 331393 81.6
        2 drugs  35835  8.8
        3 drugs  14924  3.7
      4-5 drugs  12218  3.0
     6-10 drugs   7818  1.9
      11+ drugs   3996  1.0

========================================================================
  6b. Multi-drug cases × severity cross-tab
========================================================================
           severity  multi_drug_cases
       6 DE (death)             10443
 5 LT (life-threat)              4433
4 HO (hospitalized)             22332
  3 DS (disability)               639
2 CA (cong anomaly)               254
  1 RI (req interv)                30
       0 OT (other)             27536
         no outcome              9124

            bucket   cases   pct
0  1 (monotherapy)  331393  81.6
1          2 drugs   35835   8.8
2          3 drugs   14924   3.7
3        4-5 drugs   12218   3.0
4       6-10 drugs    7818   1.9
5        11+ drugs    3996   1.0

## 7. Drug-Drug Interaction Pairs
Top co-mentioned ingredient pairs in FDA-flagged interaction cases and in all suspect cases.

In [9]:
ddi_pairs = explore.section_ddi_pairs()
ddi_pairs

========================================================================
  7. Top drug pairs in multi-drug suspect cases (FDA role='I')
========================================================================
                  drug_a                    drug_b  co_mentions
  NIRMATRELVIR\RITONAVIR                TACROLIMUS           31
               LORAZEPAM               RISPERIDONE           22
              PREDNISONE                 RITUXIMAB           21
            ARIPIPRAZOLE                 CLOZAPINE           18
            ARIPIPRAZOLE                OLANZAPINE           18
               CLOZAPINE                OLANZAPINE           18
           ACETAMINOPHEN      ESCITALOPRAM OXALATE           17
               LORAZEPAM       QUETIAPINE FUMARATE           17
    SACUBITRIL\VALSARTAN               TIRZEPATIDE           16
              QUETIAPINE               RISPERIDONE           15
            ARIPIPRAZOLE               RISPERIDONE           15
              OLANZAPINE               RISPERIDONE           14
FLUOXETINE HYDROCHLORIDE VENLAFAXINE HYDROCHLORIDE           14
     QUETIAPINE FUMARATE               RISPERIDONE           14
FLUOXETINE HYDROCHLORIDE    TRAMADOL HYDROCHLORIDE           13
             CARIPRAZINE                 CLOZAPINE           13
              BROMAZEPAM                OLANZAPINE           13
               LORAZEPAM PROPRANOLOL HYDROCHLORIDE           13
              CLONAZEPAM             VALPROIC ACID           13
             CARIPRAZINE                OLANZAPINE           13
               CLOZAPINE               RISPERIDONE           13
              OMEPRAZOLE  SERTRALINE HYDROCHLORIDE           13
              BROMAZEPAM               ZIPRASIDONE           12
           ACETAMINOPHEN              ESOMEPRAZOLE           12
              BROMAZEPAM                 LORAZEPAM           12

========================================================================
  7b. Top pairs in ALL suspect cases (PS+SS+I)
========================================================================
               drug_a        drug_b  co_mentions
           PREDNISONE     RITUXIMAB         1901
     CYCLOPHOSPHAMIDE     RITUXIMAB         1620
     CYCLOPHOSPHAMIDE   DOXORUBICIN         1272
          CARBOPLATIN    PACLITAXEL         1209
           IPILIMUMAB     NIVOLUMAB         1183
     CYCLOPHOSPHAMIDE    PREDNISONE         1156
         METHOTREXATE     RITUXIMAB         1136
     CYCLOPHOSPHAMIDE   VINCRISTINE         1123
          CARBOPLATIN PEMBROLIZUMAB         1064
         METHOTREXATE    PREDNISONE         1064
            RITUXIMAB   TOCILIZUMAB         1060
MYCOPHENOLATE MOFETIL    TACROLIMUS         1037
        DEXAMETHASONE  LENALIDOMIDE         1026
          LEFLUNOMIDE  METHOTREXATE         1023
     CYCLOPHOSPHAMIDE DEXAMETHASONE          958
         METHOTREXATE   SECUKINUMAB          945
          DOXORUBICIN     RITUXIMAB          924
           ADALIMUMAB    INFLIXIMAB          916
          DOXORUBICIN   VINCRISTINE          909
           ETANERCEPT   TOCILIZUMAB          905
            RITUXIMAB   VINCRISTINE          893
            ABATACEPT   TOCILIZUMAB          884
           ETANERCEPT  METHOTREXATE          880
           ADALIMUMAB    ETANERCEPT          853
           INFLIXIMAB  METHOTREXATE          848

                      drug_a                     drug_b  co_mentions
0     NIRMATRELVIR\RITONAVIR                 TACROLIMUS           31
1                  LORAZEPAM                RISPERIDONE           22
2                 PREDNISONE                  RITUXIMAB           21
3               ARIPIPRAZOLE                  CLOZAPINE           18
4               ARIPIPRAZOLE                 OLANZAPINE           18
5                  CLOZAPINE                 OLANZAPINE           18
6              ACETAMINOPHEN       ESCITALOPRAM OXALATE           17
7                  LORAZEPAM        QUETIAPINE FUMARATE           17
8       SACUBITRIL\VALSARTAN                TIRZEPATIDE           16
9                 QUETIAPINE                RISPERIDONE           15
10              ARIPIPRAZOLE                RISPERIDONE           15
11                OLANZAPINE                RISPERIDONE           14
12  FLUOXETINE HYDROCHLORIDE  VENLAFAXINE HYDROCHLORIDE           14
13       QUETIAPINE FUMARATE                RISPERIDONE           14
14  FLUOXETINE HYDROCHLORIDE     TRAMADOL HYDROCHLORIDE           13
15               CARIPRAZINE                  CLOZAPINE           13
16                BROMAZEPAM                 OLANZAPINE           13
17                 LORAZEPAM  PROPRANOLOL HYDROCHLORIDE           13
18                CLONAZEPAM              VALPROIC ACID           13
19               CARIPRAZINE                 OLANZAPINE           13
20                 CLOZAPINE                RISPERIDONE           13
21                OMEPRAZOLE   SERTRALINE HYDROCHLORIDE           13
22                BROMAZEPAM                ZIPRASIDONE           12
23             ACETAMINOPHEN               ESOMEPRAZOLE           12
24                BROMAZEPAM                  LORAZEPAM           12

## 8. Drug to Reaction Patterns
Common reported reactions for a few representative high-signal drugs.

In [10]:
explore.section_drug_reactions()

========================================================================
  8. Top reactions for selected drugs
========================================================================

-- ACETAMINOPHEN --
                            reaction    n
                       Off label use 1994
                    Drug ineffective 1438
Product use in unapproved indication 1191
                            Dyspnoea 1181
                                Pain 1169
                             Fatigue 1053
                              Nausea 1053
                            Vomiting 1048

-- ASPIRIN --
             reaction   n
             Dyspnoea 622
        Off label use 422
                Cough 407
                 Fall 346
                 Pain 332
               Nausea 312
     Drug ineffective 309
Drug hypersensitivity 308

-- WARFARIN --
                                         reaction   n
                                    Off label use 223
                             Condition aggravated 220
                                           Stress 182
             Product use in unapproved indication 162
                               Colitis ulcerative 150
                                 Drug ineffective 145
Loss of personal independence in daily activities 136
                                       Somnolence 136

-- METFORMIN --
Empty DataFrame
Columns: [reaction, n]
Index: []

-- ATORVASTATIN CALCIUM --
        reaction   n
          Nausea 151
        Headache 147
         Malaise 146
         Pyrexia 142
         Myalgia 132
Weight decreased 130
            Pain 126
   Off label use 121

## 9. Demographics by Severity
Age-group and sex breakdowns for major, moderate, and minor outcomes.

In [11]:
demographics = explore.section_demographics()
demographics

========================================================================
  9. Age group × severity
========================================================================
age_grp  major  moderate  minor  total
unknown  84487      3657  81685 284045
      A  12332       532  13487  68128
      E  13292       263   9256  45157
      C    580        23    620   3941
      T    592        17    643   3692
      I    185        24    131    636
      N    240       119    199    585

========================================================================
  9b. Sex × severity
========================================================================
    sex  major  moderate  minor  total
      F  51599      2430  53717 204178
      M  46361      1525  35715 137899
unknown  13694       663  16544  62544
    UNK     54        17     45   1563

   age_grp  major  moderate  minor   total
0  unknown  84487      3657  81685  284045
1        A  12332       532  13487   68128
2        E  13292       263   9256   45157
3        C    580        23    620    3941
4        T    592        17    643    3692
5        I    185        24    131     636
6        N    240       119    199     585

## 10. Training Example Preview
Reconstruct a few multi-drug severe cases end-to-end and format them as candidate fine-tuning examples.

In [12]:
training_preview = explore.section_training_example_preview(limit=3)
training_preview

========================================================================
  10. Full case reconstruction — 3 sample training examples
========================================================================

────────────────────────────────────────────────────────────────────────
CASE 231897332
────────────────────────────────────────────────────────────────────────

[demographics]
 age age_cod age_grp  sex   wt wt_cod reporter_country occp_cod
None    None    None None None   None               DE       MD

[drugs]
 drug_seq role_cod       drugname        prod_ai        route dose_amt dose_unit
        1       PS   ATORVASTATIN   ATORVASTATIN         Oral      NaN       NaN
        2       SS   ROSUVASTATIN   ROSUVASTATIN         Oral      NaN       NaN
        3       SS       PRALUENT     ALIROCUMAB Subcutaneous       75        MG
        4       SS       PRALUENT     ALIROCUMAB          NaN      NaN       NaN
        5       SS BEMPEDOIC ACID BEMPEDOIC ACID         Oral      NaN       NaN
        6       SS        REPATHA     EVOLOCUMAB Subcutaneous      NaN       NaN
        7       SS        REPATHA     EVOLOCUMAB          NaN      NaN       NaN
        8       SS      EZETIMIBE      EZETIMIBE         Oral      NaN       NaN

[indications]
 indi_drug_seq               indi_pt
             1       Hyperlipidaemia
             2       Hyperlipidaemia
             3       Hyperlipidaemia
             4 Hypercholesterolaemia
             5       Hyperlipidaemia
             6       Hyperlipidaemia
             7 Hypercholesterolaemia
             8       Hyperlipidaemia

[reactions]
                      pt drug_rec_act
Blood pressure increased         None
               Diarrhoea         None
                 Myalgia         None
              Depression         None
            Palpitations         None

[outcomes]
outc_cod
      DS
      HO

[formatted training candidate]

  USER: Patient taking ATORVASTATIN, ROSUVASTATIN, ALIROCUMAB, BEMPEDOIC ACID, EVOLOCUMAB, EZETIMIBE.
        Indications: Hyperlipidaemia, Hyperlipidaemia, Hyperlipidaemia, Hypercholesterolaemia.
        What interactions should I watch for?

  ASSISTANT (target):
    <|think|>
    Multi-drug regimen. Check each pair for known interactions.
    Reported reactions in FAERS for this combo: Blood pressure increased, Diarrhoea, Myalgia, Depression.
    Severity (FAERS): DS, HO.
    </|think>
    [generated clinical reasoning + severity-ranked report]


────────────────────────────────────────────────────────────────────────
CASE 204831466
────────────────────────────────────────────────────────────────────────

[demographics]
age age_cod age_grp sex  wt wt_cod reporter_country occp_cod
 66      YR    None   M 119     KG               DE       MD

[drugs]
 drug_seq role_cod                    drugname                        prod_ai        route dose_amt dose_unit
        7        C                ATORVASTATIN                   ATORVASTATIN      Unknown      NaN       NaN
        8        C                  TICAGRELOR                     TICAGRELOR      Unknown      NaN       NaN
        9        C                  BISOPROLOL BISOPROLOL\BISOPROLOL FUMARATE      Unknown      NaN       NaN
       10        C                 CANDESARTAN                    CANDESARTAN      Unknown      NaN       NaN
       11        C                PANTOPRAZOLE                   PANTOPRAZOLE      Unknown       40        MG
       12        C AMOXICILLIN\CLAVULANIC ACID    AMOXICILLIN\CLAVULANIC ACID      Unknown      NaN       NaN
       13        C                   TADALAFIL                      TADALAFIL      Unknown      NaN       NaN
       14        C                 CLOPIDOGREL          CLOPIDOGREL BISULFATE      Unknown      NaN       NaN
       15        C               METRONIDAZOLE                  METRONIDAZOLE      Unknown      NaN       NaN
        2       PS                    RAMIPRIL                       RAMIPRIL      Unknown      2.5        MG
        1       SS                     ASPIRIN                        ASPIRIN      Unknown      100        MG
        3       SS                 SIMVASTATIN                    SIMVASTATIN      Unknown       20        MG
        4       SS                  TAMSULOSIN                     TAMSULOSIN      Unknown      0.4        MG
        5       SS                    COSENTYX                    SECUKINUMAB Subcutaneous      300        MG
        6       SS                    COSENTYX                    SECUKINUMAB          NaN      NaN       NaN

[indications]
 indi_drug_seq                             indi_pt
             1 Product used for unknown indication
             2 Product used for unknown indication
             3 Product used for unknown indication
             4 Product used for unknown indication
             5                           Psoriasis
             6               Psoriatic arthropathy
             7 Product used for unknown indication
             8 Product used for unknown indication
             9 Product used for unknown indication
            10 Product used for unknown indication
            11 Product used for unknown indication
            12       Gastrointestinal inflammation
            13 Product used for unknown indication
            14 Product used for unknown indication
            15       Gastrointestinal inflammation

[reactions]
                                   pt drug_rec_act
                 Abdominal pain upper         None
     Gastrooesophageal reflux disease         None
                Haematocrit decreased         None
                Large intestine polyp         None
              Blood glucose increased         None
                        Haematochezia         None
                Haemoglobin decreased         None
                    Gastritis erosive         None
             Coronary artery stenosis         None
General physical health deterioration         None
         Benign prostatic hyperplasia         None
                              Colitis         None
                   Rectal haemorrhage         None
                        Hiatus hernia         None
                Myocardial infarction         None
                           Thrombosis         None
                           Renal cyst         None
                     Chest discomfort         None
         C-reactive protein increased         None
                         Haemorrhoids         None
      Mean cell haemoglobin increased         None
                              Anaemia         None
                   Disease recurrence         None
            Chronic coronary syndrome         None
                              Obesity         None
          Acute myocardial infarction         None
                    Hepatic steatosis         None
                         Diverticulum         None
     White blood cell count increased         None
 Blood alkaline phosphatase increased         None
                   Pancreatitis acute         None
       Red blood cell count decreased         None
           Blood creatinine increased         None
 Diverticulum intestinal haemorrhagic         None
                     Lipase increased         None
                      Aortic aneurysm         None

[outcomes]
outc_cod
      HO
      OT

[formatted training candidate]

  USER: Patient taking RAMIPRIL, ASPIRIN, SIMVASTATIN, TAMSULOSIN, SECUKINUMAB.
        Indications: Product used for unknown indication, Product used for unknown indication, Product used for unknown indication, Product used for unknown indication.
        What interactions should I watch for?

  ASSISTANT (target):
    <|think|>
    Multi-drug regimen. Check each pair for known interactions.
    Reported reactions in FAERS for this combo: Abdominal pain upper, Gastrooesophageal reflux disease, Haematocrit decreased, Large intestine polyp.
    Severity (FAERS): HO, OT.
    </|think>
    [generated clinical reasoning + severity-ranked report]


────────────────────────────────────────────────────────────────────────
CASE 174967172
────────────────────────────────────────────────────────────────────────

[demographics]
age age_cod age_grp sex wt wt_cod reporter_country occp_cod
 70      YR    None   M 55     KG               SE       HP

[drugs]
 drug_seq role_cod       drugname        prod_ai        route dose_amt dose_unit
       12        C     BUMETANIDE     BUMETANIDE         Oral        1        MG
       13        C     BUMETANIDE     BUMETANIDE      Unknown      NaN       NaN
       14        C       APIXABAN       APIXABAN         Oral        5        MG
       15        C       APIXABAN       APIXABAN      Unknown      NaN       NaN
       16        C    FINASTERIDE    FINASTERIDE      Unknown      NaN       NaN
       17        C    FINASTERIDE    FINASTERIDE         Oral        5        MG
       18        C     OMEPRAZOLE     OMEPRAZOLE         Oral      NaN       NaN
       19        C SPIRONOLACTONE SPIRONOLACTONE         Oral       50        MG
       20        C SPIRONOLACTONE SPIRONOLACTONE      Unknown      NaN       NaN
       21        C    SIMVASTATIN    SIMVASTATIN      Unknown      NaN       NaN
       22        C    SIMVASTATIN    SIMVASTATIN         Oral       40        MG
       23        C    USTEKINUMAB    USTEKINUMAB Subcutaneous      NaN       NaN
       24        C     METOPROLOL     METOPROLOL         Oral       25        MG
        1       PS      TADALAFIL      TADALAFIL         Oral       20        MG
        2       SS        UPTRAVI      SELEXIPAG         Oral      NaN       NaN
        3       SS        UPTRAVI      SELEXIPAG         Oral     2800        UG
        4       SS        UPTRAVI      SELEXIPAG         Oral     1200        UG
        5       SS        UPTRAVI      SELEXIPAG         Oral     2400        MG
        6       SS        UPTRAVI      SELEXIPAG         Oral     3200        UG
        7       SS        UPTRAVI      SELEXIPAG         Oral     2000        UG
        8       SS        UPTRAVI      SELEXIPAG         Oral      400        UG
        9       SS        UPTRAVI      SELEXIPAG         Oral      800        UG
       10       SS        UPTRAVI      SELEXIPAG         Oral     1600        UG
       11       SS        OPSUMIT     MACITENTAN         Oral       10        MG

[indications]
 indi_drug_seq                         indi_pt
             1 Pulmonary arterial hypertension
             2 Pulmonary arterial hypertension
             3           Anticoagulant therapy
            11 Pulmonary arterial hypertension
            12       Right ventricular failure
            13                Diuretic therapy
            14           Anticoagulant therapy
            16              Prostatic disorder
            17            Micturition disorder
            18                       Gastritis
            19       Right ventricular failure
            20                Diuretic therapy
            21                 Hyperlipidaemia
            22                      Infarction
            23                       Psoriasis
            24             Atrial fibrillation

[reactions]
                                   pt drug_rec_act
               Non-cardiac chest pain         None
                       Abdominal pain         None
                        Cholecystitis         None
                       Cholelithiasis         None
                 Abdominal distension         None
                        Sclerotherapy         None
                  Disease progression         None
   Upper gastrointestinal haemorrhage         None
                          Transfusion         None
                              Colitis         None
                            Diarrhoea         None
                              Anaemia         None
            Abdominal cavity drainage         None
      Pulmonary arterial hypertension         None
                              Ascites         None
                Haemoglobin decreased         None
                    Hepatic cirrhosis         None
                   Faeces discoloured         None
           Red blood cell transfusion         None
              Catheterisation cardiac         None
                  Portal hypertension         None
      Oesophageal varices haemorrhage         None
                     Renal impairment         None
General physical health deterioration         None
                          Haemorrhage         None
                             Dyspnoea         None
                                Cough         None
                     Weight decreased         None
                             Lethargy         None

[outcomes]
outc_cod
      HO
      DE
      LT
      OT

[formatted training candidate]

  USER: Patient taking TADALAFIL, SELEXIPAG, MACITENTAN.
        Indications: Pulmonary arterial hypertension, Pulmonary arterial hypertension, Anticoagulant therapy, Pulmonary arterial hypertension.
        What interactions should I watch for?

  ASSISTANT (target):
    <|think|>
    Multi-drug regimen. Check each pair for known interactions.
    Reported reactions in FAERS for this combo: Non-cardiac chest pain, Abdominal pain, Cholecystitis, Cholelithiasis.
    Severity (FAERS): HO, DE, LT, OT.
    </|think>
    [generated clinical reasoning + severity-ranked report]

   primaryid
0  231897332
1  204831466
2  174967172

## 11. Data Quality Flags
Quick checks for missing active ingredients, orphan rows, and suspicious ingredient strings.

In [13]:
quality_flags = explore.section_quality_flags()
quality_flags

========================================================================
  11. Data quality red flags
========================================================================
 drug_null_ai  drug_null_name  drug_orphan_no_demo  reac_orphan_no_demo  unique_cases_demo  unique_cases_drug  unique_cases_outc
        33747               0                    0                    0             406184             406184             222364

========================================================================
  11b. Suspicious active-ingredient strings (potential OCR/data-entry noise)
========================================================================
                                                                                                                                 prod_ai    n
                                                                                                                POLYETHYLENE GLYCOL 3350 1838
                                                                                                   LUTETIUM LU-177 VIPIVOTIDE TETRAXETAN 1368
CYANOCOBALAMIN\DEXPANTHENOL\NIACINAMIDE\PYRIDOXINE HYDROCHLORIDE\RIBOFLAVIN 5^-PHOSPHATE SODIUM\THIAMINE HYDROCHLORIDE\VITAMIN B COMPLEX  911
                                                          POLYETHYLENE GLYCOL 3350\POTASSIUM CHLORIDE\SODIUM BICARBONATE\SODIUM CHLORIDE  816
                                                                  ANTIHEMOPHILIC FACTOR, PEGYLATED (MW 20000) HUMAN SEQUENCE RECOMBINANT  411
                                                                                                           LUTETIUM OXODOTREOTIDE LU-177  400
      AMPHETAMINE ASPARTATE\AMPHETAMINE ASPARTATE MONOHYDRATE\AMPHETAMINE SULFATE\DEXTROAMPHETAMINE SACCHARATE\DEXTROAMPHETAMINE SULFATE  350
                                                                                                                                AZD-1222  331
                                                                                                                POLYETHYLENE GLYCOL 4000  319
                                                                                                          HYPROMELLOSE 2910 (4000 MPA.S)  155

,drug_null_ai,drug_null_name,drug_orphan_no_demo,reac_orphan_no_demo,unique_cases_demo,unique_cases_drug,unique_cases_outc
0,33747,0,0,0,406184,406184,222364

## Ad Hoc Query Cell
Edit the SQL below when you want to inspect a table directly without changing the underlying script.

In [14]:
sql = f"""
SELECT primaryid, role_cod, drugname, prod_ai
FROM {explore.SCHEMA}.drug
WHERE prod_ai IS NOT NULL
LIMIT 20
"""

explore.query(sql)

     primaryid role_cod               drugname               prod_ai
0   1001678125       PS            SANDOSTATIN    OCTREOTIDE ACETATE
1   1001678125       SS            SANDOSTATIN    OCTREOTIDE ACETATE
2   1001678125       SS            SANDOSTATIN    OCTREOTIDE ACETATE
3   1001678125       SS  SANDOSTATIN LAR DEPOT    OCTREOTIDE ACETATE
4   1001678125       SS  SANDOSTATIN LAR DEPOT    OCTREOTIDE ACETATE
5   1001678125       SS  SANDOSTATIN LAR DEPOT    OCTREOTIDE ACETATE
6   1001678125       SS  SANDOSTATIN LAR DEPOT    OCTREOTIDE ACETATE
7   1001678125       SS  SANDOSTATIN LAR DEPOT    OCTREOTIDE ACETATE
8   1001678125       SS  SANDOSTATIN LAR DEPOT    OCTREOTIDE ACETATE
9   1001678125        C            SANDOSTATIN    OCTREOTIDE ACETATE
10  1001678125        C               AFINITOR            EVEROLIMUS
11  1001678125        C               AFINITOR            EVEROLIMUS
12  1001678125        C               DEXILANT       DEXLANSOPRAZOLE
13  1001678125        C            INSULIN NOS           INSULIN NOS
14  1001678125        C              VITAMIN D         VITAMIN D NOS
15  1001678125        C                CRESTOR  ROSUVASTATIN CALCIUM
16  1001678125        C                ASPIRIN               ASPIRIN
17  1001678125        C              BUPROPION             BUPROPION
18  1001678125        C        FERROUS SULFATE       FERROUS SULFATE
19  1001678125        C                CALCIUM               CALCIUM